# Site settings
title: Machine Learning Basics
email: machine.learning.basics.github@gmail.com
description: "Machine learning notes"
baseurl: ""
url: "https://machine-learning-basics.github.io/"
twitter_username: mlbasicsgithub
github_username:  machine-learning-basics

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

